version: '3.8'
services:
  HourlyWageCalcBot:
    build:
      context: .
    image: python:3.8-slim
    container_name: HourlyWageCalcBot
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: python /app/main.py
