name: Deploy HourlyWageCalcBot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DISCORD_BUTTON_CH: ${{ secrets.DISCORD_BUTTON_CH }}
          DISCORD_LOG_CH: ${{ secrets.DISCORD_LOG_CH }}
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            export BOT_TOKEN=${BOT_TOKEN}
            export DISCORD_BUTTON_CH=${DISCORD_BUTTON_CH}
            export DISCORD_LOG_CH=${DISCORD_LOG_CH}
            cd /home/atamol/HourlyWageCalcBot
            docker-compose down
            docker-compose up -d
          EOF
