name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and deploy to server
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_1_ID: ${{ secrets.CHANNEL_1_ID }}
          CHANNEL_2_ID: ${{ secrets.CHANNEL_2_ID }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            export TOKEN=$TOKEN
            export CHANNEL_1_ID=$CHANNEL_1_ID
            export CHANNEL_2_ID=$CHANNEL_2_ID
            cd /cd/to_my_project
            docker-compose down
            docker-compose up -d
          EOF
